### ISSUE TITLE
[Bug] Channel activation issue in ni_x_series_analog_output.py and scanning

### ISSUE THREAD

**Issue by Neverhorst** [Ulm-IQO/qudi-iqo-modules#46]
### Version

current main

### What is affected by the bug?

Dragging the target position crosshair in the new scanning probe GUI causes the exception below.
Seems like channel activation in the NI analog output module is handled in a non-robust way.

### When does the bug occur?

Performed an X-Z scan after a fresh start of qudi and dragged the crosshair seconds after the scan has completed.

### How do we replicate the issue?

Seems to happen quite randomly. Did not find a reproducible way to provoke the issue.

### Expected behavior

No exception caused by dragging crosshair with NI card based scanning.

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Software\up-to-date-qudi\qudi-iqo-modules\src\qudi\hardware\interfuse\ni_scanning_probe_interfuse.py", line 732, in __ao_cursor_write_loop
    self._ni_ao().setpoints = new_voltage
  File "C:\Software\up-to-date-qudi\qudi-core\src\qudi\util\overload.py", line 159, in __setattr__
    attr = getattr(obj, name)
  File "C:\Software\up-to-date-qudi\qudi-iqo-modules\src\qudi\interface\process_control_interface.py", line 174, in setpoints
    return {ch: self.get_setpoint(ch) for ch in self.constraints.setpoint_channels}
  File "C:\Software\up-to-date-qudi\qudi-iqo-modules\src\qudi\interface\process_control_interface.py", line 174, in <dictcomp>
    return {ch: self.get_setpoint(ch) for ch in self.constraints.setpoint_channels}
  File "C:\Software\up-to-date-qudi\qudi-iqo-modules\src\qudi\hardware\ni_x_series\ni_x_series_analog_output.py", line 215, in get_setpoint
    raise RuntimeError(f'Please activate channel "{channel}" before getting setpoint')
RuntimeError: Please activate channel "ao0" before getting setpoint
```

### Contact Details

tomek.qudi@gmail.com

**Comment by timoML** [comment]
Should be fixed, thanks for reporting.
