### ISSUE TITLE
Error when connection to SMIQ with Windows 11

### ISSUE THREAD

**Issue by NicolasStaudenmaier** [Ulm-IQO/qudi-iqo-modules#73]
### Version

current main

### What is affected by the bug?

Connecting to my SMIQ throws a pyvisa error. I'm using Windows 11. However, with Windows 8 on the same machine using the same connection works perfectly. All necessary drivers should be installed from NI. Connection is established via the IEC bus and shows as connected with the Keysight Connection Expert. My other devices such as (Keysight) AWG and fastcounter connect well. 
See the error message below. 

Python 3.9
PyVisa 1.12.0

### When does the bug occur?

Activating the SMIQ

### How do we replicate the issue?

- connect SMIQ 
- check that connection is established
- activate SMIQ hardware module

### Expected behavior

Connecting without error. 

### Relevant log output

```shell
Exception during activation:

pyvisa.errors.VisaIOError: VI_ERROR_INTF_NUM_NCONFIG (-1073807195): The interface type is valid but the specified interface number is not configured.
Traceback (most recent call last):

  File "C:\Software\qudi\qudi-env\qudi-core\src\qudi\core\module.py", line 301, in __activation_callback
    self.on_activate()

  File "C:\Software\qudi\qudi-env\qudi-iqo-modules\src\qudi\hardware\microwave\mw_source_smiq.py", line 84, in on_activate
    self._device = self._rm.open_resource(self._visa_address,

  File "C:\Software\qudi\qudi-env\lib\site-packages\pyvisa\highlevel.py", line 3248, in open_resource
    info = self.resource_info(resource_name, extended=True)

  File "C:\Software\qudi\qudi-env\lib\site-packages\pyvisa\highlevel.py", line 3175, in resource_info
    ret, err = self.visalib.parse_resource_extended(self.session, resource_name)

  File "C:\Software\qudi\qudi-env\lib\site-packages\pyvisa\ctwrapper\functions.py", line 2078, in parse_resource_extended
    ret = library.viParseRsrcEx(

  File "C:\Software\qudi\qudi-env\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 226, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore

  File "C:\Software\qudi\qudi-env\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
```

**Comment by NicolasStaudenmaier** [comment]
The problem seems not to be related to Qudi. Therefore I close it. Probably it is something regarding the installation of the Keysight VISA or pyvisa.
