### ISSUE TITLE
[Bug] instreamer does not work remotely

### ISSUE THREAD

**Issue by qku** [Ulm-IQO/qudi-iqo-modules#84]
### Version

current main

### What is affected by the bug?

- Windows 10
- current main
- data instream dummy
- wavemeter instreamer (under development)

### When does the bug occur?

When calling `read_data()` of a data instreamer remotely. Other methods like `start_stream()` work fine.

### How do we replicate the issue?

1. activate data instream dummy or wavemeter instreamer and allow remote
2. connect to the module remotely
3. start the stream via the console
4. call `read_data()`

### Expected behavior

`read_data()` should return recent samples from the instreamer

### Relevant log output

```shell
---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)Cell In[3], line 1----> 1 r.read_data()File C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\netref.py:148, in BaseNetref.__getattribute__(self, name)146     return object.\_\_getattribute\_\_(self, "\_\_array\_\_")
147 else:TextHTMLCSSJavascriptCC++C#JavaPythonSqlSwiftJSON--> 148     return syncreq(self, consts.HANDLE_GETATTR, name)File C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\netref.py:63, in syncreq(proxy, handler, *args) 51 """Performs a synchronous request on the given proxy object.
 52 Not intended to be invoked directly.
 53 TextHTMLCSSJavascriptCC++C#JavaPythonSqlSwiftJSON   (...) 60 :returns: the result of the operation
 61 """
 62 conn = object.\_\_getattribute\_\_(proxy, "\_\_\_\_conn\_\_")TextHTMLCSSJavascriptCC++C#JavaPythonSqlSwiftJSON---> 63 return conn.sync_request(handler, proxy, *args)File C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\protocol.py:718, in Connection.sync_request(self, handler, *args)715 \_async_res = self.async_request(handler, \*args, timeout=timeout)
716 # \_async_res is an instance of AsyncResult, the value property invokes Connection.serve via AsyncResult.wait
717 # So, the \_recvlock can be acquired multiple times by the owning thread and warrants the use of RLockTextHTMLCSSJavascriptCC++C#JavaPythonSqlSwiftJSON--> 718 return _async_res.valueFile C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\async_.py:108, in AsyncResult.value(self)106 self.wait()
107 if self.\_is_exc:TextHTMLCSSJavascriptCC++C#JavaPythonSqlSwiftJSON--> 108     raise self._obj109 else:
110     return self.\_objTextHTMLCSSJavascriptCC++C#JavaPythonSqlSwiftJSONTypeError: __annotations__ must be set to a dict object========= Remote Traceback (1) =========Traceback (most recent call last):  File "C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\protocol.py", line 359, in _dispatch_requestres = self.\_HANDLERS\[handler](self, \*args)TextHTMLCSSJavascriptCC++C#JavaPythonSqlSwiftJSON  File "C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\protocol.py", line 853, in _handle_getattrreturn self.\_access_attr(obj, name, (), "\_rpyc_getattr", "allow_getattr", getattr)TextHTMLCSSJavascriptCC++C#JavaPythonSqlSwiftJSON  File "C:\Software\qudi\qudi-env\lib\site-packages\rpyc\core\protocol.py", line 781, in _access_attrreturn accessor(obj, name, \*args)TextHTMLCSSJavascriptCC++C#JavaPythonSqlSwiftJSON  File "C:\Software\qudi\qudi-env\lib\site-packages\qudi\core\services.py", line 245, in __getattribute__def wrapped(\*args, \*\*kwargs):TextHTMLCSSJavascriptCC++C#JavaPythonSqlSwiftJSON  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\functools.py", line 56, in update_wrappersetattr(wrapper, attr, value)TextHTMLCSSJavascriptCC++C#JavaPythonSqlSwiftJSONTypeError: __annotations__ must be set to a dict object
```

**Comment by qku** [comment]
This issue can be closed in favor of the one in qudi-core as it was discovered to be more general: https://github.com/Ulm-IQO/qudi-core/issues/56
